add rent-yacht section
o-hadalin/itduck pull request #2
Opened 2024-08-07 20:13 UTC by Pepe10k

2024-08-07 23:06 UTC, o-hadalin commented on src/css/rent-and-yacht.css
> +
Необхідно стилізувати колір підказки у полях форми згідно макету, наприклад, так:
.rent-form-input::placeholder,
.rent-form-textarea::placeholder {
    color: rgba(251, 251, 251, 0.4);
}
![image](https://github.com/user-attachments/assets/a723dc4e-21c7-45ee-8292-06e581c0c21d)

2024-08-07 23:24 UTC, o-hadalin commented on src/css/rent-and-yacht.css
> +
Тут на вибір. Я б центрував картинку по центру, наприклад, так:
.rent-container:first-child {
  margin: 0 auto;
}
По суті, при правильних падінгах на контейнер (вже виправив на 20px :)) усе гаразд, але я б вирівняв.
![image](https://github.com/user-attachments/assets/bb62e9ed-0aec-4622-a4ad-fbcdf52d3036)

2024-08-08 00:31 UTC, o-hadalin commented on src/css/rent-and-yacht.css
> +
Я б зазначив так (**але тут теж не факт**):

.rent-form-container {
    margin: 0 auto;
    width: 473px;
  }
  
Це б елемент поставило б по центру, бо у нас уже тут тягнутися нічого не повинно

2024-08-08 00:56 UTC, o-hadalin commented on src/css/rent-and-yacht.css
> +
4. Тут не той відступ між картинкою та формою - має бути 50px., щось таке варто додати:
    rent-form-container {
    margin-left: 50px;
    width: 472px;
  }
  
  **Але!** Якщо робитимеш попереднє зауваження (№ 3), то ширина 473px має сюди затягнутись автоматично. Мінус піксель - думаю описка, і нею можна знехтувати.

2024-08-08 01:02 UTC, o-hadalin requested changes
Привіт! 👋
Круто, але знайшов трохи невідповідностей макету. Усе у чотирьох коментарях зазначив. Деякі із них виключно як рекомендація.
Краще перевіряти по порядку нумерації коментарів, щоб якщо треба, то наслідувались стилі по медіа-запитам.

2024-08-08 08:36 UTC, Pepe10k commented on src/css/rent-and-yacht.css
> +
Привіт, 3 пункти зробила по твоїм рекомендаціям, окрім 2 пунтку про центрування фотки, там буквально абсолютно нічого не змінюється, центрування загального контейнера+падінги норм тримають фотку, тож залишила так.

2024-08-08 08:41 UTC, o-hadalin approved these changes

2024-08-08 08:42 UTC, o-hadalin commented
Додав ще центрування картинки. А так норм. 
Якщо додатково щось вилазитиме, правитимемо.

2024-08-08 08:43 UTC, merged

2024-08-08 08:50 UTC, Pepe10k commented
Якщо ти центрував картинку, тоді потрібно підправити відступи, бо воно перебило усі маржини нижні. 
Просто залишу щоб не забути, це можна буде вже виправити коли інші секції будуть, щоб мати загальний вигляд.